// Generated by CoffeeScript 1.9.1
(function() {
  var removeClassFromElements, removeDOMElement, removeElementsByClass;

  removeClassFromElements = function(classname) {
    var i, x;
    x = document.getElementsByClassName(classname);
    i = void 0;
    i = 0;
    while (i < x.length) {
      x[i].classList.remove(classname);
      i++;
    }
  };

  removeElementsByClass = function(className) {
    var elements;
    elements = document.getElementsByClassName(className);
    while (elements.length > 0) {
      elements[0].parentNode.removeChild(elements[0]);
    }
  };

  removeDOMElement = function(id) {
    if (document.getElementById(id)) {
      document.getElementById(id).remove();
    }
  };

  String.prototype.startsWith = function(text) {
    return this.substr(0, text.length) === text;
  };

  String.prototype.contains = function(text) {
    return this.indexOf(text) !== -1;
  };

  chrome.extension.onMessage.addListener(function(request, sender) {
    var checked, invalid, pageLinks, passed, queued, rpBox, totalvalid;
    pageLinks = document.getElementsByTagName('a');
    totalvalid = pageLinks.length;
    queued = 0;
    checked = 0;
    invalid = 0;
    passed = 0;
    rpBox = void 0;
    removeDOMElement('ALP_ReportBox');
    (function(pg) {
      var a, blacklist, blacklisted, cacheType, checkType, e, h, i, j, matas, meta_txt, r, rbClose, rbHeader, rbSettings, rcss, reportBox, reportStyle, rid, tblcss, tdlcss, tdrcss, titles;
      blacklist = request.bl;
      blacklisted = void 0;
      cacheType = request.ca;
      checkType = request.ct;
      reportStyle = document.createElement('style');
      reportStyle.setAttribute('rel', 'stylesheet');
      reportStyle.setAttribute('type', 'text/css');
      document.getElementsByTagName('head')[0].appendChild(reportStyle);
      reportStyle.appendChild(document.createTextNode('#ALP_ReportBox{font-weight: bold; width: 250px; position: fixed; right:0px; top: 0px; background: #fff; margin: 20px; padding: 0px; font-family: Arial, Helvetica, sans-serif; font-size: 14px; line-height: 14px; border-radius: 5px; z-index: 99999; box-shadow: 0px 0px 3px rgba(0,0,0,1);}'));
      reportBox = document.createElement('div');
      rbHeader = document.createElement('div');
      rbClose = document.createElement('div');
      rbClose.innerHTML = '&times;';
      rbClose.setAttribute('id', 'ALP_RB_Close');
      rbSettings = document.createElement('div');
      reportBox.setAttribute('id', 'ALP_ReportBox');
      rbHeader.innerHTML = 'Link Results';
      document.getElementsByTagName('body')[0].appendChild(reportBox);
      rpBox = document.getElementById('ALP_ReportBox');
      a = void 0;
      e = void 0;
      h = void 0;
      i = void 0;
      j = void 0;
      r = void 0;
      rcss = void 0;
      rid = void 0;
      tblcss = void 0;
      tdlcss = void 0;
      tdrcss = void 0;
      rid = 'CSS_VIEWER_PLUS';
      e = function(t) {
        return document.getElementsByTagName(t);
      };
      a = function(o, a) {
        var att;
        att = o.getAttribute(a);
        if (a === 'css' && att === null) {
          return 'css未設定';
        }
        return att;
      };
      if (document.getElementById(rid)) {
        return;
      }
      i = e('img');
      if (i.length <= 0) {
        return;
      }
      r = document.createElement('div');
      rcss = 'padding:0px;position:fixed;top:0;right:0;border:solid #ccc 1px;z-index:999;max-height:100%;overflow: auto;';
      tblcss = ' style=\'border-collapse:collapse;background:hsla(0,0%,0%,.75);\'';
      tdlcss = ' style=\'color:#fff;padding:0 .5em 0 .5em;border-bottom:solid #fff 2px;text-align:left;\'';
      tdlcss1 =' style=\'color:#fff;padding:0 .5em 0 .5em;border-bottom:solid #fff 2px;text-align:right; height: 300px;width: 300px;opacity: 0.65;\''
      tdlcss2 =' style=\'color:#fff;padding:0 .5em 0 .5em;border-bottom:solid #fff 2px;text-align:right; height: 800px;width: 300px;opacity: 0.65;\''
      tdrcss = ' style=\'padding:0 0 0 1em;border-bottom:solid #fff 2px;text-align:left;background-color:hsla(0,0%,0%,.45);color:#F0EA30;width:250px;\'';
      textariarcss = ' style=\'width: 100% ;height: 100%;\'';
      r.id = rid;
      r.style.cssText = rcss;
      h = '<style>' + "\n";
      h += '@-webkit-keyframes anime1 {\n0% {opacity: .2;}\n100% {opacity: 1;}\n}\n.cvp_blink{-webkit-animation: anime1 0.5s ease 0s infinite alternate; border:3px solid #F82F66;}\n';
      h += '</style>' + "\n";
      h += '<tr><td colspan="2" style="padding:1em 0 0 1em;border-bottom:solid #fff 2px;text-align:left;color:#fff;white-space:pre-wrap;max-width:500px;line-height:1;font-size: 12px;">';
      h += '<span class="CSS_VIEWER_CLOSE" style="background-color: hsla(0,100%,100%,1);color: #000;position: absolute;right: 0;top: 0;padding: 0.5em 1em;">Close✕</span>';
      h += '<table' + tblcss + ' class="CSS_VIEWER_TABLE">';
      h += '<tr><td' + tdlcss + '>"c"キーか"s"キーでcss取得</td></tr>';
      h += '<tr><td' + tdlcss1 + '><textarea' + textariarcss +' id="CSS_VIEWER_CONSOLE0" readonly></textarea></td></tr>';
      h += '<tr><td' + tdlcss2 + '><textarea' + textariarcss +' id="CSS_VIEWER_CONSOLE" readonly></textarea></td></tr>';
      h += '</table>';
      e('body')[0].appendChild(r);
      r.innerHTML = h;


      var script = document.createElement( 'script' );
      script.type = 'text/javascript';
      script.defer = 'defer';
      script.src = '//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js';
      r.parentNode.insertBefore(script, null);

      var script2 = document.createElement( 'script' );
      script2.type = 'text/javascript';
      script2.defer = 'defer';
      var cvh = '';
      cvh += 'function CVP(){'+"\n";
      cvh += ' console.log("CVP");'+"\n";
      // jQuery読み込み待ち
      cvh += 'if (typeof(jQuery) == "undefined") {'+"\n";
      cvh += '  setTimeout(CVP(),1000);'+"\n";
      cvh += ' return;'+"\n";
      cvh += '}'+"\n";
      cvh += ' console.log("jquery load.");'+"\n";
      // jQueryを"c$"の別名で登録
      cvh += 'var c$ = jQuery.noConflict();'+"\n";
      cvh += 'console.log("jQuery version" , c$.fn.jquery);'+"\n";
      // cvh += 'c$("#CSS_VIEWER_CONSOLE").text("ajgeo");'+"\n";
      cvh += ''+"\n";
      cvh += 'var c$target = c$("body");'+"\n";
      cvh += 'var c$target2 = c$("body");'+"\n";
      cvh += 'var cssTxt = "";'+"\n";
      cvh += 'c$( "*" ).mouseenter(function( event ) {'+"\n";
      cvh += '  c$target = c$(event.target);'+"\n";
      cvh += '      c$("#CSS_VIEWER_CONSOLE0").text(c$target[0].outerHTML + "\\n");'+"\n";

      // 枠線
      cvh += 'var elm = c$("*");'+"\n";
      cvh += 'if(elm){'+"\n";
      cvh += '  elm.removeClass("cvp_blink");'+"\n";
      cvh += '}'+"\n";
      cvh += 'c$(c$target[0]).addClass("cvp_blink");'+"\n";
      cvh += ''+"\n";


      cvh += '  var CSSRuleListObj = getMatchedCSSRules(c$target2[0], "");'+"\n";
      cvh += '  if (CSSRuleListObj) {'+"\n";
      cvh += '    for(var i=0; i<CSSRuleListObj.length; i++){'+"\n";
      cvh += '      var tmpcss = CSSRuleListObj[i].cssText;'+"\n";
      cvh += '      cssTxt += tmpcss.replace(/\.cvp_blink\s*\{.*?(})/i, "");'+"\n";

      cvh += '    }'+"\n";
      cvh += '  }'+"\n";
      cvh += '});'+"\n";
      cvh += ''+"\n";
      cvh += 'c$("body").keypress(function (e) {'+"\n";
      cvh += '  if (e.which == 99 /* c */ || e.which == 115 /* s */){'+"\n";
      cvh += '   c$("#CSS_VIEWER_CONSOLE").text(c$("#CSS_VIEWER_CONSOLE").text() + cssTxt + "\\n");'+"\n";
      cvh += '  }'+"\n";
      cvh += '});'+"\n";

      cvh += '};'+"\n";
      cvh += 'CVP();'+"\n";
      script2.appendChild(document.createTextNode(cvh));
      r.parentNode.insertBefore(script2, null);

      r.onclick = function() {};
      document.querySelector('.CSS_VIEWER_CLOSE').onclick = function() {;
        var elm = document.querySelector('#CSS_VIEWER_PLUS');
        if(elm){
          elm.remove();
        }
      };
      window.scrollTo(0, 0);

      document.getElementById('ALP_RB_Close').onclick = function() {
        removeDOMElement('ALP_ReportBox');
      };
      chrome.extension.onMessage.removeListener(doStuff);
    })(pageLinks);
    return true;
  });

}).call(this);
